# Generated by CMake 2.8.10.1

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target MOAB
ADD_LIBRARY(MOAB STATIC IMPORTED)

# Compute the installation prefix relative to this file.
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Import target "MOAB" for configuration "Release"
SET_PROPERTY(TARGET MOAB APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE DEBUG)
SET_TARGET_PROPERTIES(MOAB PROPERTIES
  #Release options to link against MOAB
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/usr/local/netcdf-4.2/lib/libnetcdf.a;/usr/local/hdf5-1.8.9-ser-gcc/lib/libhdf5.a"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libMOAB.a"
  #Debug options to link against MOAB
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "/usr/local/netcdf-4.2/lib/libnetcdf.a;/usr/local/hdf5-1.8.9-ser-gcc/lib/libhdf5_d.a"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/libMOAB.a"

  #Use LINK_FLAGS for general linking options, STATIC_LIBRARY_FLAGS can be
  #used for static linking specific options if you have dynamic and static
  #options. Both of these support overrides for each configuration type (DEBUG, RELEASE)
  )

LIST(APPEND _IMPORT_CHECK_TARGETS MOAB )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_MOAB "${_IMPORT_PREFIX}/lib/libMOAB.a" )


# Loop over all imported files and verify that they actually exist
FOREACH(target ${_IMPORT_CHECK_TARGETS} )
  FOREACH(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    IF(NOT EXISTS "${file}" )
      MESSAGE(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    ENDIF()
  ENDFOREACH()
  UNSET(_IMPORT_CHECK_FILES_FOR_${target})
ENDFOREACH()
UNSET(_IMPORT_CHECK_TARGETS)

# Cleanup temporary variables.
SET(_IMPORT_PREFIX)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
